name: Release

on:
  push:
    tags: [ 'v*.*.*' ]

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build syft
      - name: Build package
        run: python -m build
      - name: Generate SBOM
        run: syft . -o spdx-json > SBOM.spdx.json
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/*
            SBOM.spdx.json
            .compliance/*
          generate_release_notes: true
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.12.2
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
